server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: lhhu-picture-server
    #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hu_picture
    username: root
    password: 123456
  # Spring默认限制文件上传最大为1MB，开放更大权限
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: isDelete    # 对应字段
      logic-delete-value: 1           # 已删除
      logic-not-delete-value: 0       # 未删除

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lhhu.lhhupictureserver.controller